In [1]:
import sklearn
sklearn.__version__

'0.21.2'

In [2]:
#load_boston:회귀 분석용 보스턴 집값
#load_diabetes: 회귀 분석용 당뇨병 자료
#load_linnerud: 회귀 분석용 linnerud 자료
#load_iris: 분류용 붓꽃 자료
#load_digits: 분류용 숫자 필기 이미지 자료
#load_wine: 분류용 포도주 자료
#load_breast_cancer: 유방암 자료

from sklearn.datasets import load_iris

In [3]:
iris_dataset = load_iris()
print('iris_dataset key:{}'.format(iris_dataset.keys()))

iris_dataset key:dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [4]:
print(iris_dataset['data'][:10])
print('shape of data: {}'.format(iris_dataset['data'].shape))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
shape of data: (150, 4)


In [5]:
print(iris_dataset['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
print(iris_dataset['target'])
print(iris_dataset['target_names'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [7]:
data = iris_dataset['data']
target = iris_dataset['target']
print(data[:5])
print(target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [8]:
from sklearn.model_selection import train_test_split

#정렬된 데이터인 경우 앞의 몇 개, 뒤의 몇 개 식으로 데이터를 뽑아오면 편중될 수 있으므로 random하게 뽑아옴
train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'],  # train_input, test_input
                                                                   target,  # train_label, test_label
                                                                   test_size=0.25,  # test용 25%, 학습용 75%
                                                                   random_state=42)  # 동일하게 데이터를 뽑도록 random값을 지정함
print('shape of train_input: {}'.format(train_input.shape))
print('shape of test_input: {}'.format(test_input.shape))
print('shape of train_label: {}'.format(train_label.shape))
print('shape of test_label: {}'.format(test_label.shape))

shape of train_input: (112, 4)
shape of test_input: (38, 4)
shape of train_label: (112,)
shape of test_label: (38,)


In [9]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1) # k값.가장 가까운 1개를 찾음.

knn.fit(train_input, train_label)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [10]:
import numpy as np
new_input=np.array([[6.1, 2.8, 4.7, 1.2]])  # 새로운 붓꽃 데이터

In [11]:
knn.predict(new_input)  # 그에 대한 예측 결과 0, 1, 2중 하나

array([1])

In [12]:
predict_label = knn.predict(test_input)
print(predict_label)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]


In [13]:
# 원래 정답과 예측된 값 비교
print('test accuracy {:.2f}'.format(np.mean(predict_label==test_label)))  # 1이면 100% 매치

test accuracy 1.00
